apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: jasperreports-server-repository
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: jasperreports-server-repository
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: jasperreports-server-repository
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: jasperreports-server-repository
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jasperreports-server-repository
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:9
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim